"""Docker-backed execution of untrusted analysis code.

No Python code generated by a model is evaluated in the FastAPI process.  Each
request receives a short-lived, non-networked, non-root container with a
read-only root filesystem and explicit CPU, memory, process-count, and wall
clock limits.
"""

from __future__ import annotations

import logging
import io
import tarfile
import threading
import time
from pathlib import Path
from typing import Any

import docker
from docker.errors import APIError, DockerException
from docker.types import LogConfig, Ulimit
from requests.exceptions import ReadTimeout
from requests.exceptions import ConnectionError as RequestsConnectionError
from urllib3.exceptions import ReadTimeoutError

from app.core.config import Settings, get_settings
from app.schemas.sandbox import SandboxResult, SandboxStatus


class DockerSandboxExecutor:
    """Run one Python script in a fresh constrained Docker container."""

    MAX_CODE_BYTES = 64 * 1024
    MAX_LOG_BYTES = 256 * 1024

    def __init__(self, settings: Settings | None = None, client: Any | None = None) -> None:
        self.settings = settings or get_settings()
        self._client = client

    @property
    def client(self) -> Any:
        if self._client is None:
            self._client = docker.from_env()
        return self._client

    def execute(self, code: str, dataset_path: Path | None = None, cancelled=None) -> SandboxResult:
        """Execute code and always remove its container, even after timeout."""
        started = time.monotonic()
        if len(code.encode("utf-8")) > self.MAX_CODE_BYTES or "\x00" in code:
            raise ValueError("Code must be at most 64 KiB and contain no NUL bytes.")
        container: Any | None = None
        finished = threading.Event()
        watcher = None
        try:
            command = ["-I", "-u", "-c", code]
            if dataset_path is not None:
                if not dataset_path.is_file() or dataset_path.stat().st_size > 128 * 1024**2:
                    raise ValueError("Dataset missing or exceeds sandbox input limit")
                # A trusted bootstrap waits until the complete archive has arrived.
                command = ["-I", "-u", "-c",
                           "import os,time,runpy\n"
                           "deadline=time.monotonic()+15\n"
                           "while not os.path.exists('/tmp/input-ready'):\n"
                           " if time.monotonic()>deadline: raise TimeoutError('input not ready')\n"
                           " time.sleep(.02)\n"
                           "runpy.run_path('/tmp/analysis.py',run_name='__main__')"]
            container = self.client.containers.create(
                image=self.settings.sandbox_image,
                command=command,
                working_dir="/workspace",
                user="65534:65534",
                network_disabled=True,
                mem_limit=f"{self.settings.sandbox_memory_limit_mb}m",
                memswap_limit=f"{self.settings.sandbox_memory_limit_mb}m",
                nano_cpus=self.settings.sandbox_cpu_nano_cpus,
                pids_limit=self.settings.sandbox_pids_limit,
                read_only=True,
                tmpfs={"/tmp": "rw,noexec,nosuid,size=192m" if dataset_path else "rw,noexec,nosuid,size=64m"},
                cap_drop=["ALL"],
                security_opt=["no-new-privileges:true"],
                ulimits=[Ulimit(name="nofile", soft=256, hard=256),
                         Ulimit(name="core", soft=0, hard=0)],
                log_config=LogConfig(type="json-file", config={"max-size": "1m", "max-file": "1"}),
                detach=True,
                auto_remove=False,
            )
            container.start()
            if dataset_path is not None:
                with io.BytesIO() as archive:
                    with tarfile.open(fileobj=archive, mode="w") as tar:
                        for name, value in (("dataset.parquet", dataset_path.read_bytes()),
                                            ("analysis.py", code.encode()), ("input-ready", b"ready")):
                            info = tarfile.TarInfo(name)
                            info.size, info.mode, info.uid, info.gid = len(value), 0o400, 65534, 65534
                            tar.addfile(info, io.BytesIO(value))
                    archive.seek(0)
                    container.put_archive("/tmp", archive)
            if cancelled is not None:
                def cancel_watch():
                    while not finished.wait(.1):
                        if cancelled.is_set():
                            try:
                                container.kill()
                            except DockerException:
                                pass
                            return
                watcher = threading.Thread(target=cancel_watch, daemon=True)
                watcher.start()
            try:
                wait_result = container.wait(timeout=self.settings.sandbox_timeout_seconds)
            except (ReadTimeout, RequestsConnectionError) as error:
                # Requests wraps streamed HTTP response read timeouts in
                # ConnectionError on some transports, including Docker's Unix socket.
                if isinstance(error, RequestsConnectionError) and not any(
                    isinstance(cause, ReadTimeoutError) for cause in error.args
                ):
                    raise
                container.kill()
                stdout, stderr = self._logs(container)
                return SandboxResult(
                    status=SandboxStatus.TIMED_OUT,
                    stdout=stdout,
                    stderr=stderr or f"Execution exceeded the {self.settings.sandbox_timeout_seconds}-second sandbox limit.",
                    duration_ms=self._duration_ms(started),
                    timed_out=True,
                )

            stdout, stderr = self._logs(container)
            exit_code = int(wait_result.get("StatusCode", 1))
            container.reload()
            state = container.attrs.get("State", {})
            oom_killed = bool(state.get("OOMKilled"))
            if oom_killed:
                return SandboxResult(
                    status=SandboxStatus.MEMORY_LIMIT_EXCEEDED,
                    stdout=stdout,
                    stderr=stderr or f"Execution exceeded the {self.settings.sandbox_memory_limit_mb}MB sandbox memory limit.",
                    exit_code=exit_code,
                    duration_ms=self._duration_ms(started),
                    memory_limit_exceeded=True,
                )
            return SandboxResult(
                status=SandboxStatus.COMPLETED if exit_code == 0 else SandboxStatus.FAILED,
                stdout=stdout,
                stderr=stderr,
                exit_code=exit_code,
                duration_ms=self._duration_ms(started),
            )
        except (APIError, DockerException, OSError) as error:
            return SandboxResult(
                status=SandboxStatus.ENGINE_ERROR,
                stderr=f"Sandbox engine unavailable: {error}",
                duration_ms=self._duration_ms(started),
            )
        finally:
            finished.set()
            if watcher is not None:
                watcher.join(timeout=1)
            if container is not None:
                try:
                    container.remove(force=True)
                except (APIError, DockerException):
                    logging.getLogger(__name__).exception("Failed to remove sandbox container")

    @classmethod
    def _logs(cls, container: Any) -> tuple[str, str]:
        outputs = []
        for is_stdout in (True, False):
            stream = container.logs(stdout=is_stdout, stderr=not is_stdout, stream=True, follow=False)
            output = bytearray()
            try:
                for chunk in stream:
                    remaining = cls.MAX_LOG_BYTES - len(output)
                    output.extend(chunk[:remaining])
                    if len(chunk) > remaining:
                        output.extend(b"\n[output truncated]")
                        break
            finally:
                if hasattr(stream, "close"):
                    stream.close()
            outputs.append(output.decode("utf-8", "replace"))
        return outputs[0], outputs[1]

    @staticmethod
    def _duration_ms(started: float) -> int:
        return int((time.monotonic() - started) * 1000)
