"""Docker-backed execution of untrusted analysis code.

No Python code generated by a model is evaluated in the FastAPI process.  Each
request receives a short-lived, non-networked, non-root container with a
read-only root filesystem and explicit CPU, memory, process-count, and wall
clock limits.
"""

from __future__ import annotations

import io
import tarfile
import time
from typing import Any

import docker
from docker.errors import APIError, DockerException
from requests.exceptions import ReadTimeout

from app.core.config import Settings, get_settings
from app.schemas.sandbox import SandboxResult, SandboxStatus


class DockerSandboxExecutor:
    """Run one Python script in a fresh constrained Docker container."""

    _SCRIPT_PATH = "/workspace/analysis.py"

    def __init__(self, settings: Settings | None = None, client: Any | None = None) -> None:
        self.settings = settings or get_settings()
        self._client = client

    @property
    def client(self) -> Any:
        if self._client is None:
            self._client = docker.from_env()
        return self._client

    def execute(self, code: str) -> SandboxResult:
        """Execute code and always remove its container, even after timeout."""
        started = time.monotonic()
        container: Any | None = None
        try:
            container = self.client.containers.create(
                image=self.settings.sandbox_image,
                command=[self._SCRIPT_PATH],
                working_dir="/workspace",
                user="65534:65534",
                network_disabled=True,
                mem_limit=f"{self.settings.sandbox_memory_limit_mb}m",
                nano_cpus=self.settings.sandbox_cpu_nano_cpus,
                pids_limit=self.settings.sandbox_pids_limit,
                read_only=True,
                tmpfs={"/tmp": "rw,noexec,nosuid,size=64m"},
                cap_drop=["ALL"],
                security_opt=["no-new-privileges:true"],
                detach=True,
                auto_remove=False,
            )
            container.put_archive("/workspace", self._script_archive(code))
            container.start()
            try:
                wait_result = container.wait(timeout=self.settings.sandbox_timeout_seconds)
            except ReadTimeout:
                container.kill()
                stdout, stderr = self._logs(container)
                return SandboxResult(
                    status=SandboxStatus.TIMED_OUT,
                    stdout=stdout,
                    stderr=stderr or "Execution exceeded the 10-second sandbox limit.",
                    duration_ms=self._duration_ms(started),
                    timed_out=True,
                )

            stdout, stderr = self._logs(container)
            exit_code = int(wait_result.get("StatusCode", 1))
            container.reload()
            state = container.attrs.get("State", {})
            oom_killed = bool(state.get("OOMKilled"))
            if oom_killed:
                return SandboxResult(
                    status=SandboxStatus.MEMORY_LIMIT_EXCEEDED,
                    stdout=stdout,
                    stderr=stderr or "Execution exceeded the 512MB sandbox memory limit.",
                    exit_code=exit_code,
                    duration_ms=self._duration_ms(started),
                    memory_limit_exceeded=True,
                )
            return SandboxResult(
                status=SandboxStatus.COMPLETED if exit_code == 0 else SandboxStatus.FAILED,
                stdout=stdout,
                stderr=stderr,
                exit_code=exit_code,
                duration_ms=self._duration_ms(started),
            )
        except (APIError, DockerException, OSError) as error:
            return SandboxResult(
                status=SandboxStatus.ENGINE_ERROR,
                stderr=f"Sandbox engine unavailable: {error}",
                duration_ms=self._duration_ms(started),
            )
        finally:
            if container is not None:
                try:
                    container.remove(force=True)
                except (APIError, DockerException):
                    pass

    @classmethod
    def _script_archive(cls, code: str) -> bytes:
        encoded = code.encode("utf-8")
        archive = io.BytesIO()
        with tarfile.open(fileobj=archive, mode="w") as tar:
            info = tarfile.TarInfo(name="analysis.py")
            info.size = len(encoded)
            info.mode = 0o500
            info.uid = 65534
            info.gid = 65534
            tar.addfile(info, io.BytesIO(encoded))
        return archive.getvalue()

    @staticmethod
    def _logs(container: Any) -> tuple[str, str]:
        stdout, stderr = container.logs(stdout=True, stderr=True, demux=True)
        return (stdout or b"").decode("utf-8", "replace"), (stderr or b"").decode("utf-8", "replace")

    @staticmethod
    def _duration_ms(started: float) -> int:
        return int((time.monotonic() - started) * 1000)
